# All available configuration can be found here:
# https://www.algolia.com/doc/api-client/symfony/configuration/
algolia_search:
    #serializer: jms_serializer
    prefix: '%env(APP_ENV)%_'
    batchSize: 25
    # doctrineSubscribedEvents: ['postPersist']
    doctrineSubscribedEvents: []
    indices:
    - name: ingredients
      class: App\Entity\Ingredient
      enable_serializer_groups: true
