# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    filter_sets:
        thumb: 
            quality: 75
            filters:
                thumbnail:
                    size: [240, 140]
                    mode: outbound
        medium: 
            quality: 75
            filters:
                thumbnail:
                    size: [450, 300]
                    mode: outbound
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
